import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { supplyId, itemName, description, imageUrl } = await req.json();
    console.log('Generating illustration for:', itemName);

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    // Create a simple, focused prompt for minimalist line drawing
    // Extract key terms from item name for simpler illustration
    const simplifiedName = itemName.toLowerCase().includes('blanket') 
      ? 'outdoor blanket on grass'
      : itemName.toLowerCase().includes('table')
      ? 'folding table'
      : itemName.toLowerCase().includes('chair')
      ? 'folding chair'
      : itemName.toLowerCase().includes('bucket')
      ? 'utility bucket'
      : itemName;
    
    const prompt = `Create a minimalist black and white line drawing illustration of a ${simplifiedName}. 
    
Style requirements:
- Simple, clean line art similar to technical catalog illustrations
- Black lines on white background
- No shading, no gradients, no color
- Clear, recognizable silhouette
- Product-focused perspective
- Technical drawing aesthetic like McMaster-Carr catalog
- IMPORTANT: NO TEXT, NO LABELS, NO CAPTIONS within the image itself
- Only draw the object, do not include any written words or descriptions in the image

Make it simple, iconic, and immediately recognizable. The drawing should contain ONLY the visual representation of the item, with absolutely no text or labels anywhere in the image.`;

    console.log('Calling Lovable AI for image generation...');

    // Generate the illustration using Lovable AI
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image',
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ],
        modalities: ['image', 'text']
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI gateway error:', aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please try again later.' }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      if (aiResponse.status === 402) {
        return new Response(
          JSON.stringify({ error: 'Payment required. Please add credits to your Lovable AI workspace.' }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      throw new Error(`AI generation failed: ${errorText}`);
    }

    const aiData = await aiResponse.json();
    console.log('AI response received');

    // Extract the generated image
    const generatedImage = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!generatedImage) {
      throw new Error('No image generated by AI');
    }

    // Update the supply record with the illustration URL
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { error: updateError } = await supabase
      .from('supplies')
      .update({ illustration_url: generatedImage })
      .eq('id', supplyId);

    if (updateError) {
      console.error('Error updating supply:', updateError);
      throw updateError;
    }

    console.log('Illustration generated and saved successfully');

    return new Response(
      JSON.stringify({ 
        success: true, 
        illustrationUrl: generatedImage 
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in generate-illustration:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Unknown error occurred' 
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});