// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbmmfgivhqzhjyneyelu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ibW1mZ2l2aHF6aGp5bmV5ZWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzI4NjMsImV4cCI6MjA2NTk0ODg2M30.ZijxdB9N3BQycz0H_5VeLKwPbLzEDV_bAO1K1guLHYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);